const Map<String, dynamic> lang = {
  "en": {
    "waterTitle": "Water Reminder",
    "waterBody": "Time to drink water",
    "medicineBody": "Time to Take Medicine",
    "medicineTitle": "Medication Reminder",
    "open": "Open",
    "closed": "Closed",
    "noPhoto": "No Photo",
    "remove": "Remove",
    "checkNumber": "Please, check number of ingredients",
    "changeLanguage": "Change Language",
    "sendMessage": "Send a message",
    "timesADay": "Times a day",
    "hi": "Hi",
    "add": "Add",
    "recipes": "Recipes",
    "medicines": "Medicines",
    "dailyMedicines": "Daily Medicine",
    "toDoList": "To Do List",
    "water": "Water",
    "dailyDrinkTargetOne": "Daily Drink Target: ",
    "main": "Main",
    "map": "Map",
    "chat": "Chat",
    "areYouSure": "Are You Sure?",
    "cancel": "Cancel",
    "done": "Done",
    "editProfile": "Edit Profile",
    "privacyNPolicy": "Privacy and Policy",
    "license": "License",
    "logOut": "Log Out",
    "loading": "Loading",
    "welcomeBack": "Welcome Back",
    "enterUrEmail": "Enter your e-mail",
    "password": "Password",
    "placePassword": "Place the password here",
    "login": "Login",
    "dontHaveAcc": "Don't have an account yet?",
    "signUp": "Sign up",
    "createAcc": "Create an account",
    "fullName": "Full Name",
    "enterName": "Enter your name",
    "atLeast8Char": "At least 8 characters",
    "bothUppAndLow": "Both uppercase and lowercase characters",
    "atLeast1Num": "At least one Number",
    "termAndCon": "By continuing you accept our Privacy Policy and Term of Use",
    "alreadyHavaAcc": "Already have an account?",
    "fillForm": "Fill forms or Tick Box",
    "somethingWentWrong": "Something went wrong",
    "setPhoto": "Set Photo",
    "search": "Search",
    "myPantry": "My Pantry",
    "tapHere": "Tap Here →",
    "pantry": "Pantry",
    "generate": "Generate",
    "beforeMeal": "Before Meal",
    "afterMeal": "After Meal",
    "duringTheMeal": "During the Meal",
    "takingWithMeals": "Taking with meals",
    "dosage": "Dosage",
    "addSupplement": "Add a Supplement",
    "suppName": "Supplement Name",
    "suppForm": "Supplement Form",
    "typeSuppName": "Type a name of supplement",
    "tablet": "Tablet",
    "sachet": "Sachet",
    "pill": "Pill",
    "drop": "Drop",
    "times": "times a day",
    "dailyDrinkTargetTwo": "Daily Drink Target",
    "confirm": "Confirm that you have just drunk water",
    "nextTime": "Next Time",
    "addIngredients": "Add Ingredients",
    "thisMedHasAll": "This medicine has already been added",
    "pleaseFillForm": "Type a name of supplement",
    "firstAdvice":
        "Do not drink cold water immediately after hot drinks like tea or coffee",
    "secondAdvice":
        "Drink water an hour after the meal to allow the body to absorb the nutrients.",
    "thirdAdvice":
        "Cloudy water is caused by tiny air bubbles in the water which make it appear white. They're not harmful and quickly clear, rising from the bottom of the glass upwards.",
    "waterExc": "You can add after at least an hour",
    "finished": "Finished Unsuccessfully",
    "pleasePickAnImage": "Please, Pick an Image",
    "english": "English",
    "uzbek": "Uzbek",
    "russian": "Russian",
    "price": "Price",
    "manu": "Manufacturer",
  },
  "uz": {
    "price": "Narxi",
    "manu": "Ishlab Chiqaruvchi",
    "waterTitle": "Suv haqida eslatma",
    "waterBody": "Suv ichish vaqti ",
    "medicineBody": "Dori qabul qilish vaqti",
    "medicineTitle": "Dori haqida eslatma",
    "open": "Ochiq",
    "closed": "Yopiq",
    "noPhoto": "Rasm yo'q",
    "remove": "O'chirish",
    "checkNumber": "Iltimos, ingredientlar sonini tekshiring",
    "changeLanguage": "Tilni o'zgartirish",
    "sendMessage": "Xabar yuboring",
    "pleasePickAnImage": "Iltimos, Rasm Tanlang",
    "finished": "Muvaffaqiyatsiz yakunlandi",
    "firstAdvice":
        "Choy yoki qahva kabi issiq ichimliklardan keyin darhol sovuq suv ichmang",
    "secondAdvice":
        "Ovqatdan keyin bir soat o'tgach, tanaga ozuqa moddalarini olish uchun suv iching.",
    "thirdAdvice":
        "Bulutli suv suvdagi mayda havo pufakchalari tufayli yuzaga keladi, bu esa uni oq rangga aylantiradi. Ular zararli emas va tez tozalanadi, stakan ostidan yuqoriga ko'tariladi.",
    "suppForm": "Dori turi",
    "addIngredients": "Ingredientlar qo'shish",
    "hi": "Salom",
    "add": "Qo'shish",
    "recipes": "Retseptlar",
    "medicines": "Dorilar",
    "dailyMedicines": "Kunlik Dori Iste'moli",
    "toDoList": "Ro'yxatini qilish",
    "water": "Suv",
    "dailyDrinkTargetOne": "Kunlik Suv Chegarasi: ",
    "thisMedHasAll": "Ushbu dori allaqachon qo'shilgan",
    "main": "Asosiy",
    "map": "Xarita",
    "chat": "Chat",
    "areYouSure": "Ishonchingiz komilmi?",
    "cancel": "Bekor Qilish",
    "done": "Bajarildi",
    "editProfile": "Profilni tahrirlash",
    "privacyNPolicy": "Maxfiylik va siyosat",
    "license": "Litsenziya",
    "logOut": "Chiqish",
    "loading": "Yuklanmoqda",
    "welcomeBack": "Xush Kelibsiz",
    "enterUrEmail": "e-mail kiriting",
    "password": "Parol",
    "placePassword": "Parolni Kiriting",
    "login": "Tizimga kirish",
    "dontHaveAcc": "Hali hisobingiz yoʻqmi?",
    "signUp": "Ro'yxatdan o'tish",
    "createAcc": "Hisob yaratish",
    "fullName": "Ism",
    "enterName": "Ismingizni kiriting",
    "atLeast8Char": "Kamida 8 ta belgi",
    "bothUppAndLow": "Ham katta, ham kichik harflar",
    "atLeast1Num": "Kamida bitta raqam",
    "termAndCon":
        "Davom etish orqali siz Maxfiylik siyosatimiz va Foydalanish shartlarini qabul qilasiz",
    "alreadyHavaAcc": "Allaqachon hisobingiz bormi?",
    "fillForm": "Shakllarni to'ldiring yoki katakchani belgilang",
    "somethingWentWrong": "Nimadir noto'g'ri bajarildi",
    "setPhoto": "Rasmni o'rnatish",
    "search": "Qidirmoq",
    "myPantry": "Mening oshxonam",
    "tapHere": "Bu yerni Bosing →",
    "pantry": "Oshxona",
    "generate": "Yaratish",
    "beforeMeal": "Ovqatlanishdan Oldin",
    "afterMeal": "Ovqatlanishdan Keyin",
    "duringTheMeal": "Ovqatlanish Paytida",
    "takingWithMeals": "Ovqatlanish bilan birga qabul qilish",
    "dosage": "Doza",
    "addSupplement": "Dori Qo'shish",
    "suppName": "Dori Nomi",
    "typeSuppName": "Dorini nomini kiriting",
    "tablet": "Tabletka",
    "sachet": "Kichkina paketcha",
    "pill": "Kapsula",
    "drop": "Tomchi",
    "times": "marta kuniga ",
    "dailyDrinkTargetTwo": "Kunlik Suv Chegarasi",
    "confirm": "Hozirgina suv ichganingizni tasdiqlang",
    "nextTime": "Keying Vaqt",
    "pleaseFillForm": "Iltimos, anketani toʻldiring",
    "timesADay": "Marta kuniga",
    "waterExc": "Siz kamida bir soatdan keyin qo'shishingiz mumkin",
    "english": "Ingliz Tili",
    "uzbek": "O'zbek Tili",
    "russian": "Rus Tili",
  },
  "ru": {
    "price": "Цена",
    "manu": "Производитель",
    "waterTitle": "Water Reminder",
    "waterBody": "Время пить воду",
    "medicineBody": "Время принять лекарство",
    "medicineTitle": "Напоминание о лекарстве",
    "open": "Открыто",
    "closed": "Закрыто",
    "noPhoto": "Нет фото",
    "remove": "Удалить",
    "checkNumber": "Пожалуйста, проверьте количество ингредиентов",
    "english": "Английский",
    "uzbek": "Узбекский",
    "russian": "Русский",
    "changeLanguage": "Изменить язык",
    "sendMessage": "Отправить сообщение",
    "pleasePickAnImage": "Пожалуйста, выберите изображение",
    "finished": "Завершено неудачно",
    "waterExc": "Вы можете добавить через час",
    "firstAdvice":
        "Не пейте холодную воду сразу после горячих напитков, таких как чай или кофе.",
    "secondAdvice":
        "Пейте воду через час после еды, чтобы организм усвоил питательные вещества.",
    "thirdAdvice":
        "Мутность воды вызвана крошечными пузырьками воздуха в воде, которые делают ее белой. Они безвредны и быстро очищаются, поднимаясь со дна стакана вверх.",
    "timesADay": "Раз в день",
    "pleaseFillForm": "Введите название лекарства",
    "suppForm": "Форма дополнения",
    "thisMedHasAll": "Это лекарство уже добавлено",
    "addIngredients": "Добавить ингредиенты",
    "hi": "Привет",
    "add": "Добавить",
    "recipes": "Рецепты",
    "medicines": "Лекарства",
    "dailyMedicines": "Ежедневные лекарства",
    "toDoList": "Список дел",
    "water": "Вода",
    "dailyDrinkTargetOne": "Ежедневная цель питья: ",
    "main": "Главное",
    "map": "Карта",
    "chat": "Чат",
    "areYouSure": "Вы уверены?",
    "cancel": "Отменить",
    "done": "Сделано",
    "editProfile": "Редактировать профиль",
    "privacyNPolicy": "Конфиденциальность и политика",
    "license": "Лицензия",
    "logOut": "Выйти",
    "loading": "Загрузка",
    "welcomeBack": "Добро пожаловать",
    "enterUrEmail": "Введите адрес электронной почты",
    "password": "Пароль",
    "placePassword": "Поместите пароль здесь",
    "login": "Войти",
    "dontHaveAcc": "Ещё нет аккаунта?",
    "signUp": "Зарегистрироваться",
    "createAcc": "Создать аккаунт",
    "fullName": "Полное имя",
    "enterName": "Введите ваше имя",
    "atLeast8Char": "Не менее 8 символов",
    "bothUppAndLow": "Как прописные, так и строчные символы",
    "atLeast1Num": "Хотя бы одна цифра",
    "termAndCon": "Продолжая, вы принимаете нашу Политику конфиденциальности и Условия использования",
    "alreadyHavaAcc": "У вас уже есть аккаунт?",
    "fillForm": "Заполните формы или отметьте поле",
    "somethingWentWrong": "Что-то пошло не так",
    "setPhoto": "Установить фото",
    "search": "Поиск",
    "myPantry": "Моя кладовая",
    "tapHere": "Нажмите здесь →",
    "pantry": "Кладовая",
    "generate": "Генерировать",
    "beforeMeal": "Перед едой",
    "afterMeal": "После еды",
    "duringTheMeal": "Во время еды",
    "takingWithMeals": "Принимать с едой",
    "dosage": "Доза",
    "addSupplement": "Добавить лекарство",
    "suppName": "Название лекарства",
    "typeSuppName": "Введите название лекарства",
    "tablet": "Таблетка",
    "sachet": "Пакетик",
    "pill": "Пилюля",
    "drop": "Капелька",
    "times": "Раза в день",
    "dailyDrinkTargetTwo": "Ежедневная цель питья",
    "confirm": "Подтвердите, что вы только что выпили воду",
    "nextTime": "В следующий раз"
  }
};
