const Map<String,dynamic> ingredientsProvider = {
    
    "Vegetables & Greens": [
        "garlic",
        "onion",
        "bell pepper",
        "carrot",
        "scallion",
        "tomato",
        "potato",
        "red onion",
        "celery",
        "jalapeno",
        "avocado",
        "shallot",
        "zucchini",
        "cherry tomato",
        "cucumber",
        "spinach",
        "sweet corn",
        "sweet potato",
        "broccoli",
        "pumpkin",
        "baby greens",
        "cauliflower",
        "cabbage",
        "asparagus",
        "kale",
        "arugula",
        "leek",
        "eggplant",
        "lettuce",
        "butternut squash",
        "romaine",
        "beetroot",
        "brussels sprout",
        "fennel",
        "radish",
        "sun dried tomato",
        "red cabbage",
        "artichoke",
        "new potato",
        "summer squash",
        "mixed greens",
        "parsnip",
        "baby carrot",
        "poblano pepper",
        "mixed vegetable",
        "serrano pepper",
        "sweet pepper",
        "watercress",
        "green tomato",
        "iceberg",
        "mashed potatoes",
        "horseradish",
        "chard",
        "pimiento",
        "butter lettuce",
        "spaghetti squash",
        "napa cabbage",
        "celeriac",
        "hash browns",
        "water chestnut",
        "turnip",
        "bok choy",
        "okra",
        "thai chile pepper",
        "radicchio",
        "acorn squash",
        "corn cob",
        "pearl onion",
        "tenderstem broccoli",
        "plantain",
        "baby bok choy",
        "leaf lettuce",
        "jicama",
        "endive",
        "pepperoncini",
        "habanero pepper",
        "corn husk",
        "collard greens",
        "french-fried onions",
        "daikon",
        "baby corn",
        "belgian endive",
        "rutabaga",
        "broccoli rabe",
        "ancho chile peppers",
        "boston lettuce",
        "yam",
        "fresno chile",
        "microgreens",
        "kohlrabi",
        "frisee",
        "delicata squash",
        "anaheim pepper",
        "cress",
        "broccoli slaw",
        "golden beet",
        "pea shoots",
        "gem lettuce",
        "alfalfa",
        "jerusalem artichoke"
    ],
    "Mushrooms": [
        "button mushroom",
        "shiitake mushroom",
        "portobello mushroom",
        "porcini",
        "wild mushroom",
        "oyster mushroom",
        "mixed mushrooms",
        "chestnut mushroom",
        "enoki mushroom",
        "black fungus",
        "black truffle",
        "morel mushrooms",
        "field mushroom",
        "king oyster mushroom",
        "shimeji mushroom",
        "straw mushroom",
        "dried chinese mushroom",
        "maitake",
        "trumpet mushroom",
        "white truffle",
        "white fungus",
        "pioppini",
        "boletus",
        "snow fungus",
        "white beech mushroom",
        "huitlacoche",
        "matsutake",
        "nameko",
        "djon djon mushroom",
        "mixed asian mushrooms",
        "puffball",
        "honey fungus",
        "caesar's mushroom",
        "candy cap mushrooms",
        "lion\u2019s mane mushroom"
    ],
    "Fruits": [
        "lemon",
        "lime",
        "apple",
        "orange",
        "banana",
        "raisins",
        "pineapple",
        "mango",
        "peach",
        "date",
        "coconut",
        "craisins",
        "pear",
        "pomegranate",
        "grape",
        "watermelon",
        "rhubarb",
        "dried apricot",
        "kiwi",
        "grapefruit",
        "plum",
        "fig",
        "mandarin",
        "apricot",
        "currant",
        "prunes",
        "sultanas",
        "cantaloupe",
        "papaya",
        "passion fruit",
        "tamarind",
        "nectarine",
        "dried fig",
        "chestnut",
        "meyer lemon",
        "honeydew melon",
        "clementine",
        "dried fruit",
        "persimmon",
        "melon",
        "tangerine",
        "apple chips",
        "dried mango",
        "quince",
        "guava",
        "kumquat",
        "banana chips",
        "jackfruit",
        "dragon fruit",
        "mixed fruit",
        "asian pear",
        "lychee",
        "kaffir lime",
        "star fruit",
        "bitter melon",
        "tender coconut",
        "pomelo",
        "prickly pear",
        "chestnut puree",
        "yuzu",
        "calamansi",
        "granadilla",
        "mixed peel",
        "kokum",
        "dried lime",
        "tangelo",
        "sweet lime",
        "dried lemon",
        "custard-apple",
        "durian",
        "young jackfruit",
        "dried tamarind",
        "honey date",
        "ice-apple",
        "physalis",
        "tamarillo",
        "jujube",
        "longan",
        "finger lime",
        "bitter orange",
        "feijoa",
        "dried persimmons",
        "rambutan",
        "rose apple",
        "dried orange slice",
        "fig leaves",
        "loquat",
        "crabapple",
        "freeze-dried pineapple",
        "soursop",
        "pluot",
        "hog plum",
        "bergamot orange",
        "luo han guo",
        "mamey",
        "sapote",
        "aloo bukhara",
        "green ume plum",
        "kiwano",
        "seagrape"
    ],
    "Berries": [
        "strawberry",
        "blueberry",
        "raspberry",
        "cranberry",
        "cherry",
        "blackberry",
        "berry mix",
        "maraschino cherry",
        "dried tart cherry",
        "juniper berry",
        "sour cherry",
        "dried blueberries",
        "goji berry",
        "freeze-dried strawberry",
        "gooseberry",
        "lingonberry",
        "canned sour cherry",
        "mulberry",
        "amla",
        "acai berry",
        "elderberry",
        "canned cherry",
        "huckleberry",
        "dried elderberry",
        "barberry",
        "dried berries",
        "sea buckthorn",
        "saskatoon berry",
        "hawthorn",
        "rosehip",
        "boysenberry",
        "cloudberry",
        "freeze-dried berries",
        "aronia berry",
        "chokeberry",
        "loganberry",
        "blackcurrant leaves",
        "haskap berry",
        "dewberry",
        "sloe berry",
        "oregon grape"
    ],
    "Nuts & Seeds": [
        "walnut",
        "pecan",
        "almond",
        "sesame seed",
        "cashew",
        "peanut",
        "pine nut",
        "pistachio",
        "chia",
        "flax",
        "slivered almonds",
        "pumpkin seeds",
        "hazelnut",
        "poppy seed",
        "sunflower seeds",
        "macadamia",
        "chopped nuts",
        "hemp hearts",
        "nigella seeds",
        "mixed nuts",
        "brazil nut",
        "mixed seeds",
        "onion seed",
        "watermelon seeds",
        "melon seeds",
        "honey-roasted peanuts",
        "white chia",
        "lotus seeds",
        "trail mix",
        "basil seeds",
        "candlenut",
        "peanut brittle",
        "honey-roasted almond",
        "chironji",
        "tigernuts",
        "sunflower sprouts",
        "apricot kernels",
        "palm seeds",
        "keto trail mix",
        "bar\u00f9kas",
        "indian almond"
    ],
    "Cheeses": [
        "parmesan",
        "cream cheese",
        "cheddar",
        "mozzarella",
        "feta",
        "ricotta",
        "sharp cheddar",
        "monterey jack",
        "blue cheese",
        "goat cheese",
        "fresh mozzarella",
        "swiss cheese",
        "pecorino",
        "gruyere",
        "mascarpone",
        "cottage cheese",
        "american cheese",
        "provolone",
        "mexican cheese blend",
        "pepper jack",
        "brie",
        "paneer",
        "fontina",
        "queso fresco",
        "quark",
        "gouda",
        "cotija",
        "asiago",
        "smoked cheese",
        "halloumi",
        "chevre",
        "manchego",
        "italian cheese blend",
        "neufchatel",
        "burrata",
        "havarti",
        "colby",
        "herb cream cheese",
        "grana-padano",
        "muenster",
        "camembert",
        "string cheese",
        "soft cheese",
        "stilton",
        "raclette",
        "cheddar-jack cheese",
        "colby-jack cheese",
        "taleggio",
        "jarlsberg cheese",
        "oaxaca",
        "labneh",
        "edam",
        "creamy cheese wedge",
        "fromage blanc",
        "cheese powder",
        "asadero",
        "marble cheese",
        "leicester",
        "mizithra",
        "lancashire",
        "kefalotyri",
        "kasseri",
        "babybel",
        "panela cheese",
        "seasoned feta cheese",
        "comt\u00e9",
        "longhorn",
        "wensleydale",
        "graviera",
        "scamorza",
        "amul cheese",
        "cambozola",
        "cheshire cheese",
        "chenna",
        "hard goat cheese",
        "anthotyro",
        "kashkaval",
        "sheep cheese",
        "reblochon",
        "quick-melt cheese",
        "robiola",
        "brick cheese",
        "farmer's cheese",
        "manouri",
        "mimolette",
        "queso quesadilla",
        "caciocavallo",
        "requeij\u00e3o",
        "vacherin",
        "brown cheese",
        "gloucester",
        "port salut",
        "derby cheese",
        "fontal",
        "salad cheese",
        "truffle cheese",
        "epoisses cheese",
        "maasdam",
        "petit-suisse",
        "sbrinz"
    ],
    "Dairy & Eggs": [
        "butter",
        "egg",
        "milk",
        "heavy cream",
        "sour cream",
        "buttermilk",
        "yogurt",
        "greek yogurt",
        "cream",
        "whipped cream",
        "ghee",
        "shortening",
        "half and half",
        "sweetened condensed milk",
        "ice cream",
        "margarine",
        "evaporated milk",
        "creme fraiche",
        "condensed milk",
        "frosting",
        "milk powder",
        "curd",
        "thickened cream",
        "lemon curd",
        "custard",
        "dulce de leche",
        "chocolate frosting",
        "kefir",
        "sherbet",
        "chocolate milk",
        "liquid egg substitute",
        "whey",
        "hung curd",
        "quail egg",
        "buttermilk powder",
        "frozen yogurt",
        "khoya",
        "milk cream",
        "coffee creamer",
        "clotted cream",
        "goat milk",
        "sour milk",
        "cheese curd",
        "ganache",
        "cajeta",
        "duck egg",
        "salted egg",
        "skyr",
        "raw milk",
        "chantilly",
        "lime curd",
        "powdered coffee creamer",
        "milkfat",
        "yogurt starter",
        "rainbow sherbet",
        "strawberry frosting",
        "amul butter",
        "honey butter",
        "century egg",
        "goat butter",
        "strawberry cream cheese",
        "orange curd",
        "dahi",
        "goat yogurt",
        "pumpkin spice coffee creamer",
        "bulgarian yogurt",
        "chocolate milk powder",
        "tvorog",
        "liquid rennet",
        "strawberry milk",
        "ayran",
        "cuajada",
        "yogurt drink",
        "pickled egg",
        "sheep milk",
        "starter culture",
        "kashk",
        "ostrich egg",
        "yoplait whips",
        "buffalo milk",
        "goat kefir",
        "lebneh",
        "sheep yogurt"
    ],
    "Dairy-Free & Meat Substitutes": [
        "coconut milk",
        "almond milk",
        "almond butter",
        "tofu",
        "coconut cream",
        "non-dairy milk",
        "vegan butter",
        "soy milk",
        "extra firm tofu",
        "silken tofu",
        "kala namak salt",
        "coconut butter",
        "egg replacer",
        "vegan mayonnaise",
        "vegan cheese",
        "cashew butter",
        "tempeh",
        "coconut yogurt",
        "vegan cream cheese",
        "non-dairy yogurt",
        "seed butter",
        "oat milk",
        "rice milk",
        "cashew milk",
        "nut butter",
        "vegan sour cream",
        "textured vegetable protein",
        "soy yogurt",
        "vegan worcestershire",
        "vegan mozzarella",
        "non-dairy creamer",
        "vegan sausage",
        "coconut whipped cream",
        "coconut powder",
        "smoked tofu",
        "soy cream",
        "seitan",
        "coconut milk powder",
        "non-dairy whipped topping",
        "nut milk",
        "non-dairy cream",
        "vegan burger patty",
        "condensed coconut milk",
        "vegan ground beef",
        "hemp protein",
        "pulled oats",
        "soy curls",
        "vegan pesto",
        "vegan feta",
        "soy chorizo",
        "hazelnut butter",
        "hemp milk",
        "vegan bacon",
        "vegan beef",
        "coconut paste",
        "vegetable suet",
        "dairy-free ice-cream",
        "vegan chicken",
        "almond-coconut milk",
        "banana blossom",
        "vegan fish sauce",
        "vegetarian hot dog",
        "hazelnut milk",
        "soy milk powder",
        "vegan meatballs",
        "almond-milk yogurt",
        "vegan cream cheese frosting",
        "almond creamer",
        "falafel mix",
        "ready-made falafel",
        "vegan gravy",
        "cashew cheese sauce",
        "coconut fat",
        "hazelnut creamer",
        "quorn",
        "soy-free butter",
        "tofurky",
        "cashew cream cheese",
        "flax milk",
        "macadamia butter",
        "vegan nutella",
        "cricket flour",
        "okara",
        "egg tofu",
        "protein drink",
        "macadamia milk",
        "vegan taco meat",
        "walnut taco meat",
        "vegan yogurt starter",
        "banana milk",
        "latik",
        "vegan chicken nuggets",
        "vegan starter culture",
        "walnut milk",
        "rice cream",
        "soy quark",
        "vegan roe",
        "vegetarian rennet"
    ],
    "Meats": [
        "bacon",
        "ground beef",
        "beef steak",
        "ham",
        "sweet italian sausage",
        "pork loin",
        "prosciutto",
        "sausage",
        "beef roast",
        "ground pork",
        "pork chops",
        "pork fillet",
        "beef stew meat",
        "pepperoni",
        "chorizo",
        "pancetta",
        "pork shoulder",
        "pork ribs",
        "ground lamb",
        "smoked sausage",
        "breakfast sausage",
        "hot dog",
        "beef sirloin",
        "salami",
        "brisket",
        "beef short ribs",
        "deli ham",
        "leg of lamb",
        "kielbasa",
        "pork belly",
        "andouille",
        "boneless lamb",
        "ground pork sausage",
        "ground sausage",
        "roast beef",
        "bacon bits",
        "pork roast",
        "hot italian sausage",
        "beef ribs",
        "lamb shoulder",
        "pork spare ribs",
        "veal steak",
        "lamb chops",
        "mutton",
        "bone-in ham",
        "lamb shank",
        "canadian bacon",
        "beef sausage",
        "ham steak",
        "bratwurst",
        "venison",
        "pulled pork",
        "pork butt",
        "ham hock",
        "frozen meatballs",
        "rabbit",
        "mixed ground meat",
        "pork cutlets",
        "veal cutlet",
        "soup bones",
        "lamb loin",
        "rack of lamb",
        "pork back ribs",
        "mexican chorizo",
        "black forest ham",
        "pork steak",
        "smoked ham hock",
        "oxtail",
        "serrano ham",
        "raw chorizo",
        "beef liver",
        "pastrami",
        "back bacon",
        "cocktail sausage",
        "hard salami",
        "salt pork",
        "veal shank",
        "ground venison",
        "beef shank",
        "blood sausage",
        "dried beef",
        "lap cheong",
        "gammon joint",
        "country ham",
        "ground bison",
        "mortadella",
        "fresh sausage",
        "bologna",
        "smoked pork chop",
        "lamb neck",
        "beef suet",
        "sausage patty",
        "burger patty",
        "veal roast",
        "beef shoulder",
        "steak tips",
        "veal chops",
        "venison steak",
        "snail",
        "wild boar"
    ],
    "Poultry": [
        "chicken breast",
        "chicken thighs",
        "cooked chicken",
        "ground turkey",
        "whole chicken",
        "chicken leg",
        "whole turkey",
        "chicken wings",
        "turkey breast",
        "ground chicken",
        "rotisserie chicken",
        "chicken tenders",
        "turkey sausage",
        "chicken sausage",
        "duck",
        "turkey bacon",
        "duck breast",
        "boneless chicken",
        "chicken livers",
        "cornish hen",
        "deli turkey",
        "smoked turkey",
        "turkey meat",
        "chicken quarters",
        "quail",
        "smoked turkey sausage",
        "smoked chicken",
        "turkey leg",
        "pheasant",
        "goose",
        "chicken bones",
        "turkey ham",
        "turkey pepperoni",
        "turkey thigh",
        "foie gras",
        "turkey meatballs",
        "turkey neck",
        "chicken giblets",
        "turkey giblets",
        "turkey wing",
        "chicken nuggets",
        "turkey burger",
        "chicken gizzards",
        "ground turkey sausage",
        "chicken andouille",
        "smoked turkey leg",
        "chicken italian sausage",
        "crispy chicken strips",
        "ostrich",
        "popcorn chicken",
        "chicken necks",
        "chicken feet",
        "pulled chicken",
        "deli chicken",
        "smoked duck breast",
        "pigeon",
        "turkey kielbasa",
        "wild game bird",
        "duck confit",
        "turkey liver",
        "chicken meatballs",
        "chicken-apple sausage",
        "duck liver",
        "guinea fowl",
        "smoked turkey wings",
        "chicken roast",
        "chicken schnitzel",
        "grouse",
        "goose liver",
        "turkey bones",
        "turkey lunch meat",
        "turkey roast",
        "capon",
        "smoked turkey bacon",
        "chicken bacon",
        "turkey rissoles",
        "chicken kebab",
        "chicken ham",
        "duck neck",
        "chicken frames",
        "duck bacon",
        "chicken gyros",
        "chicken patty",
        "chicken ribs",
        "turkey tail",
        "chicken milanesa"
    ],
    "Fish": [
        "salmon",
        "smoked salmon",
        "cod",
        "tilapia",
        "tuna steak",
        "whitefish",
        "halibut",
        "trout",
        "sea bass",
        "red snapper",
        "fish fillets",
        "catfish",
        "swordfish",
        "sardines",
        "sole",
        "mahi mahi",
        "mackerel",
        "surimi",
        "smoked trout",
        "haddock",
        "smoked haddock",
        "caviar",
        "monkfish",
        "flounder",
        "perch",
        "salt cod",
        "hake",
        "pollock",
        "smoked mackerel",
        "rainbow trout",
        "sea bream",
        "carp",
        "cuttlefish",
        "herring",
        "grouper",
        "salmon roe",
        "roe",
        "barramundi",
        "black cod",
        "kingfish",
        "orange roughy",
        "pomfret",
        "turbot",
        "rockfish",
        "bangus",
        "branzino",
        "dried anchovy",
        "arctic char",
        "eel",
        "lemon sole",
        "yellowtail",
        "fresh anchovy",
        "pickled herring",
        "battered fish",
        "pike",
        "walleye",
        "john dory",
        "swai fish",
        "fresh mackerel",
        "salmon trout",
        "basa fish",
        "bluefish",
        "smoked eel",
        "sturgeon",
        "fish balls",
        "gurnard",
        "red mullet",
        "rohu fish",
        "fish heads",
        "plaice",
        "pompano",
        "dried fish",
        "flathead",
        "smoked fish",
        "shark meat",
        "smoked herring",
        "whiting",
        "fish cake",
        "salmon burger meat",
        "garoupa",
        "gilt-head bream",
        "pangasius",
        "salt herring",
        "soused herring",
        "tinapa",
        "zander",
        "amberjack",
        "bottarga",
        "mullet",
        "skipjack tuna",
        "tiny fish",
        "korean fish cake",
        "marlin",
        "threadfin",
        "beluga caviar",
        "bombay duck",
        "fish pie mix",
        "kamaboko",
        "pilchards",
        "shirasu"
    ],
    "Seafood & Seaweed": [
        "shrimp",
        "prawns",
        "crab",
        "scallop",
        "mussel",
        "clam",
        "squid",
        "nori",
        "lobster",
        "oyster",
        "lobster tail",
        "crawfish",
        "octopus",
        "kombu",
        "dried shrimp",
        "bay scallop",
        "wakame",
        "soft-shell crab",
        "baby squid",
        "scampi",
        "king crab",
        "mixed seafood",
        "squid ink",
        "dried prawns",
        "dulse seaweed",
        "roasted seaweed",
        "smoked oyster",
        "kelp",
        "kizami nori",
        "hijiki",
        "salted shrimp",
        "conch",
        "yaki-nori",
        "arame",
        "mud crab",
        "sea urchin",
        "abalone",
        "seaweed salad",
        "dulse",
        "smoked mussel",
        "sea snails",
        "aonori",
        "prepared crab cake",
        "sea lettuce",
        "korean seaweed",
        "ogo seaweed",
        "seaweed caviar",
        "sea moss",
        "langoustine"
    ],
    "Herbs & Spices": [
        "cinnamon",
        "parsley",
        "cilantro",
        "cumin",
        "basil",
        "thyme",
        "ginger root",
        "garlic powder",
        "oregano",
        "nutmeg",
        "chili flake",
        "chili powder",
        "paprika",
        "cayenne",
        "rosemary",
        "bay leaf",
        "turmeric",
        "clove",
        "chile pepper",
        "onion powder",
        "ginger powder",
        "chive",
        "dill",
        "mint",
        "green cardamom",
        "fresh mint",
        "smoked paprika",
        "coriander powder",
        "coriander",
        "sage",
        "allspice",
        "cracked pepper",
        "peppercorn",
        "mustard seed",
        "white pepper",
        "curry leaves",
        "fennel seed",
        "tarragon",
        "saffron",
        "asafoetida",
        "star anise",
        "marjoram",
        "lemongrass",
        "caraway",
        "chipotle",
        "garlic granules",
        "celery seed",
        "fenugreek",
        "onion flake",
        "matcha powder",
        "ancho chile powder",
        "sumac",
        "fenugreek seed",
        "chipotle powder",
        "dried parsley flakes",
        "kashmiri red chilli",
        "edible flowers",
        "thai basil",
        "aniseed",
        "lavender",
        "kaffir lime leaves",
        "chervil",
        "carom seeds",
        "mace",
        "mexican oregano",
        "mango powder",
        "black mustard seed",
        "black cardamom",
        "saffron strands",
        "dried chilies",
        "guajillo pepper",
        "pink peppercorn",
        "hot paprika",
        "lemon thyme",
        "arbol chile pepper",
        "galangal",
        "garlic flakes",
        "dried cilantro",
        "lemon balm",
        "dill seed",
        "green peppercorn",
        "aleppo pepper",
        "wasabi powder",
        "savory herb",
        "achiote seeds",
        "sorrel",
        "pandan leaves",
        "gochugaru",
        "saigon cinnamon",
        "lemongrass paste",
        "black cumin",
        "shiso",
        "anardana",
        "vietnamese mint",
        "celery powder",
        "dried orange peel",
        "espelette pepper",
        "lemon verbena",
        "raw stevia",
        "achiote paste"
    ],
    "Sugar & Sweeteners": [
        "sugar",
        "brown sugar",
        "confectioners\u2019 sugar",
        "honey",
        "maple syrup",
        "corn syrup",
        "coconut sugar",
        "molasses",
        "stevia",
        "agave nectar",
        "sugar syrup",
        "erythritol",
        "vanilla sugar",
        "demerara sugar",
        "caramel syrup",
        "jaggery",
        "chocolate syrup",
        "raw sugar",
        "golden syrup",
        "cinnamon sugar",
        "grenadine",
        "liquid stevia",
        "coarse sugar",
        "salted caramel syrup",
        "sanding sugar",
        "dark corn syrup",
        "sucralose",
        "monk fruit sweetener",
        "maple sugar",
        "blackstrap molasses",
        "glucose",
        "rock sugar",
        "confectioners' sweetener",
        "xylitol",
        "jam sugar",
        "brown sugar substitute",
        "brown rice syrup",
        "strawberry syrup",
        "vanilla syrup",
        "ginger syrup",
        "orgeat",
        "pancake syrup",
        "rice malt syrup",
        "raspberry syrup",
        "black treacle",
        "date syrup",
        "date paste",
        "coconut syrup",
        "mint syrup",
        "treacle",
        "rice syrup",
        "manuka honey",
        "maple butter",
        "blueberry syrup",
        "apple syrup",
        "blackberry syrup",
        "allulose",
        "piloncillo",
        "cherry syrup",
        "hibiscus syrup",
        "fresh sugar cane",
        "sorghum syrup",
        "hazelnut syrup",
        "glycerine",
        "white chocolate sauce",
        "pumpkin spice syrup",
        "lucuma powder",
        "black sugar",
        "cranberry syrup",
        "cane syrup",
        "mango syrup",
        "malt syrup",
        "hot honey",
        "gula melaka",
        "elderberry syrup",
        "sweet'n low",
        "fructose",
        "honey powder",
        "grape syrup",
        "berry syrup",
        "brown butter syrup",
        "date sugar",
        "gum syrup",
        "inulin",
        "mastic gum",
        "irish cream syrup",
        "prickly pear syrup",
        "cookie butter syrup",
        "creamed honey",
        "buttermilk syrup",
        "flavored syrup",
        "malt sugar",
        "chocolate sugar",
        "truffle honey",
        "aspartame",
        "peanut butter syrup",
        "rose milk",
        "butter pecan syrup",
        "carob syrup",
        "coffee-flavored syrup"
    ],
    "Seasonings & Spice Blends": [
        "italian seasoning",
        "seasoned salt",
        "curry",
        "garam masala",
        "pumpkin pie spice",
        "mustard powder",
        "taco seasoning",
        "cajun seasoning",
        "dry ranch seasoning",
        "white miso",
        "lemon &amp; pepper seasoning",
        "poultry seasoning",
        "liquid smoke",
        "chinese five spice",
        "red curry",
        "old bay seasoning",
        "herbes de provence",
        "chaat masala",
        "creole seasoning",
        "steak seasoning",
        "mixed spice",
        "fleur de sel",
        "thai red curry paste",
        "mixed herbs",
        "green curry",
        "barbecue seasoning",
        "apple pie spice",
        "za'atar",
        "ras el hanout",
        "seafood seasoning",
        "bagel seasoning",
        "fajita seasoning",
        "all-purpose seasoning",
        "tandoori spice",
        "pickling spice",
        "caribbean jerk seasoning",
        "gravy mix",
        "garlic-pepper seasoning",
        "msg",
        "greek seasoning",
        "sambar powder",
        "adobo seasoning",
        "teriyaki marinade",
        "garlic &amp; herb seasoning",
        "smoked salt",
        "dash seasoning",
        "red miso",
        "hot curry",
        "salt-free seasoning",
        "yellow miso",
        "carne asada seasoning",
        "bouquet garni",
        "curing salt",
        "pav bhaji masala",
        "dukkah",
        "mexican seasoning",
        "seasoned pepper",
        "tajin seasoning",
        "crab boil seasoning",
        "shichimi togarashi",
        "truffle salt",
        "furikake",
        "biryani masala",
        "togarashi",
        "chipotle seasoning",
        "meat masala",
        "harissa spice blend",
        "chicken gravy mix",
        "chana masala",
        "au jus mix",
        "mushroom seasoning",
        "berbere",
        "brown miso",
        "chicken taco seasoning",
        "gingerbread spice",
        "popcorn seasoning",
        "blackening seasoning",
        "chai masala",
        "fines herbes",
        "pizza seasoning",
        "chili-lime seasoning",
        "kitchen king masala",
        "shawarma seasoning",
        "panang curry",
        "thai seasoning",
        "lemon &amp; herb seasoning",
        "mulling spices",
        "hawaiian salt",
        "sriracha seasoning",
        "coffee rub",
        "mesquite seasoning",
        "salad seasoning",
        "fish masala",
        "tom yum paste",
        "fresh mixed herbs",
        "southwest chipotle seasoning",
        "panch phoron",
        "baharat",
        "fermented bean curd",
        "piri-piri seasoning"
    ],
    "Baking": [
        "flour",
        "vanilla",
        "baking powder",
        "baking soda",
        "cornstarch",
        "yeast",
        "dark chocolate chips",
        "chocolate chips",
        "whole-wheat flour",
        "almond flour",
        "self-raising flour",
        "shredded coconut",
        "cornmeal",
        "coconut flake",
        "gelatin",
        "pastry flour",
        "corn flour",
        "cream of tartar",
        "baking mix",
        "cake flour",
        "coconut flour",
        "almond meal",
        "bread flour",
        "unbleached all-purpose flour",
        "white baking chips",
        "gluten-free flour",
        "rice flour",
        "desiccated coconut",
        "tapioca starch",
        "chickpea flour",
        "yellow cake mix",
        "canned pie filling",
        "xanthan gum",
        "oat flour",
        "whole-wheat pastry flour",
        "candy sprinkles",
        "spelt",
        "brownie mix",
        "arrowroot flour",
        "flaxseed meal",
        "potato starch",
        "butterscotch chips",
        "chocolate cake mix",
        "jello",
        "peanut butter chips",
        "crystallized ginger",
        "buckwheat flour",
        "brown rice flour",
        "pectin",
        "rye flour",
        "psyllium husk",
        "refined flour",
        "semolina flour",
        "glutinous rice flour",
        "pancake mix",
        "muffin mix",
        "marzipan",
        "coffee bean",
        "toffee bits",
        "cornbread mix",
        "spice cake mix",
        "devil's food cake mix",
        "sorghum flour",
        "masa harina",
        "potato flakes",
        "cinnamon chips",
        "agar agar",
        "red velvet cake mix",
        "matzo meal",
        "sago",
        "cassava flour",
        "sugar cookie mix",
        "vital wheat gluten",
        "hazelnut flour",
        "meringue powder",
        "citric acid",
        "baking chips",
        "coconut chips",
        "finger millet flour",
        "quinoa flour",
        "fondant",
        "angel food cake mix",
        "white cornmeal",
        "whipped cream stabilizer",
        "mint baking chips",
        "millet flour",
        "mincemeat",
        "gluten-free baking flour",
        "einkorn flour",
        "self-rising cornmeal",
        "gluten-free self-raising flour",
        "peanut flour",
        "sweet bean paste",
        "carob powder",
        "tapioca pearls",
        "teff flour",
        "potato flour",
        "guar gum",
        "seasoned flour",
        "instant flour"
    ],
    "Pre-Made Doughs & Wrappers": [
        "pie crust",
        "puff pastry",
        "pizza crust",
        "phyllo",
        "biscuit dough",
        "refrigerated crescent rolls",
        "dumpling wrapper",
        "rice paper",
        "sourdough starter",
        "cookie dough",
        "egg roll wrapper",
        "bread dough",
        "butter puff pastry",
        "frozen dinner roll",
        "wontons",
        "cinnamon roll dough",
        "dosa batter",
        "puff pastry shells",
        "gyoza wrapper",
        "idli batter",
        "fresh pasta dough",
        "potsticker wrappers",
        "chocolate pie crust",
        "croissant dough",
        "tofu skins",
        "brisee",
        "sausage rolls",
        "kataifi",
        "korean rice cake",
        "corn dogs",
        "tortilla dough",
        "empanada wrapper",
        "rough-puff pastry",
        "gingerbread cookie dough",
        "yufka",
        "cob loaf",
        "egg wrap",
        "samosa sheet",
        "brick pastry"
    ],
    "Grains & Cereals": [
        "rolled oats",
        "rice",
        "quinoa",
        "basmati rice",
        "brown rice",
        "risotto rice",
        "breakfast cereal",
        "couscous",
        "rice cereal",
        "semolina",
        "wild rice",
        "jasmine rice",
        "polenta",
        "granola cereal",
        "bulgur",
        "pearl barley",
        "farro",
        "barley",
        "wheat germ",
        "grits",
        "steel cut oats",
        "millet",
        "oat bran",
        "glutinous rice",
        "sushi rice",
        "instant rice",
        "hominy",
        "red quinoa",
        "wheat bran",
        "raw buckwheat",
        "poha",
        "wheat berries",
        "instant oats",
        "black rice",
        "yellow rice",
        "fine semolina",
        "muesli",
        "amaranth",
        "kasha",
        "quinoa flakes",
        "puffed rice",
        "cracked wheat",
        "pearled farro",
        "freekeh",
        "paella rice",
        "sorghum",
        "red rice",
        "mexican rice",
        "idli rice",
        "cream of wheat",
        "rice pilaf",
        "weetabix",
        "barnyard millet",
        "black glutinous rice",
        "jambalaya rice mix",
        "puffed quinoa",
        "cilantro lime rice",
        "dirty rice mix",
        "hulled barley",
        "finger millet",
        "foxtail millet",
        "matta rice",
        "rye berries",
        "kodo millet",
        "spelt flakes",
        "oat groats",
        "teff",
        "little millet",
        "rye flakes",
        "gluten-free breakfast cereal",
        "puffed amaranth",
        "coconut rice",
        "puffed wheat",
        "amaranth flakes",
        "puffed kamut",
        "bamboo rice",
        "pearled sorghum",
        "shirataki rice",
        "gr\u00fcnkern",
        "jeera rice",
        "fonio",
        "cream of rice",
        "kamut flakes",
        "ka\u00f1iwa",
        "proso millet"
    ],
    "Legumes": [
        "peas",
        "green beans",
        "chickpea",
        "black beans",
        "kidney beans",
        "white beans",
        "lentils",
        "pinto beans",
        "snow peas",
        "snap peas",
        "red lentils",
        "cannellini beans",
        "bean sprouts",
        "edamame",
        "green lentils",
        "urad dal",
        "lima beans",
        "chana dal",
        "fava beans",
        "black-eyed peas",
        "moong dal",
        "split peas",
        "pigeon peas",
        "red beans",
        "mung bean sprout",
        "soybeans",
        "mung beans",
        "string beans",
        "yellow split peas",
        "black lentils",
        "borlotti beans",
        "aquafaba",
        "chana",
        "snake beans",
        "mixed beans",
        "yellow lentils",
        "fermented black beans",
        "kala chana",
        "black gram",
        "wax beans",
        "dried peas",
        "pink beans",
        "lentil sprouts",
        "white pea",
        "black soybeans",
        "field peas",
        "gigantes",
        "flageolets",
        "horse gram",
        "soy sprouts",
        "cluster beans",
        "honey beans",
        "winged beans",
        "brown beans",
        "moth beans",
        "mayocoba beans",
        "castelluccio lentils",
        "golden wax beans",
        "chickpea sprouts",
        "hara chana",
        "lupini beans",
        "natto",
        "hyacinth beans",
        "petai",
        "scarlet runner beans",
        "soy flakes"
    ],
    "Pasta": [
        "short-cut pasta",
        "spaghetti",
        "macaroni",
        "egg noodle",
        "spiral pasta",
        "lasagna",
        "linguine",
        "fettuccine",
        "orzo",
        "pasta shell",
        "bow-tie pasta",
        "noodle",
        "tortellini",
        "rice noodles",
        "rigatoni",
        "gnocchi",
        "angel hair pasta",
        "ramen noodles",
        "vermicelli",
        "tagliatelle",
        "soba noodles",
        "ravioli",
        "ziti",
        "orecchiette",
        "israeli couscous",
        "zoodles",
        "udon noodles",
        "ditalini",
        "pappardelle",
        "glass noodles",
        "rice vermicelli",
        "gluten-free pasta",
        "mac 'n cheese",
        "penne rigate",
        "manicotti",
        "bucatini",
        "cannelloni",
        "thai rice noodles",
        "brown rice pasta",
        "rotelle",
        "chicken ramen",
        "shirataki noodles",
        "pierogi",
        "sweet potato noodles",
        "instant noodle",
        "acini di pepe",
        "cavatelli",
        "soup pasta",
        "somen noodles",
        "yakisoba noodles",
        "hakka noodles",
        "beef ravioli",
        "kelp noodles",
        "fideo pasta",
        "radiatore",
        "spaetzle",
        "paccheri",
        "kluski noodles",
        "matzo farfel",
        "black bean pasta",
        "yolk-free noodles",
        "spinach fettuccine",
        "rice-a-roni",
        "fregola",
        "frozen dumplings",
        "beef tortellini",
        "banh pho",
        "butternut squash noodles",
        "mie noodle",
        "trahanas",
        "busiate",
        "lobster ravioli",
        "mafalde",
        "misua",
        "palmini",
        "trottole",
        "mandu",
        "pasta salad mix",
        "pot pie noodle",
        "quinoa pasta",
        "bean pasta",
        "bean sheets",
        "hilopites",
        "jjolmyeon",
        "naengmyeon noodles",
        "yuba noodles"
    ],
    "Bread & Salty Snacks": [
        "bread",
        "bread crumbs",
        "panko",
        "flour tortillas",
        "corn tortillas",
        "crackers",
        "baguette",
        "tortilla chips",
        "pita",
        "pretzels",
        "sourdough bread",
        "rustic italian bread",
        "popcorn",
        "croutons",
        "whole-wheat tortillas",
        "english muffin",
        "brioche",
        "italian bread crumbs",
        "rye bread",
        "flatbread",
        "dry-roasted peanuts",
        "stuffing mix",
        "naan",
        "potato chips",
        "cornbread",
        "taco shells",
        "tater tots",
        "bagel",
        "corn chips",
        "unpopped popcorn",
        "croissants",
        "pork rinds",
        "pumpernickel",
        "muffin",
        "sweet bread",
        "pita chips",
        "potato bread",
        "gluten free bread",
        "hawaiian rolls",
        "breadsticks",
        "focaccia",
        "gluten-free bread crumbs",
        "tostada shells",
        "crispy fried onions",
        "matzo",
        "yeast extract spread",
        "garlic bread",
        "challah",
        "roasted gram",
        "crostini",
        "rice cake",
        "panettone",
        "sweet potato fries",
        "sev",
        "papad",
        "vegetable chips",
        "spinach wraps",
        "plantain chips",
        "cheetos",
        "roasted chickpeas",
        "chapati",
        "crumpet",
        "seed bread",
        "keto bread",
        "bread bowl",
        "sprouted grain bread",
        "frozen onion rings",
        "corn nuts",
        "corn muffin",
        "rusks",
        "fruit bread",
        "rice crackers",
        "pav bun",
        "pretzel bun",
        "roti bread",
        "boboli",
        "crispbread",
        "chocolate muffin",
        "milk bread",
        "popcorn shrimp",
        "prawn crackers",
        "wasabi peas",
        "yorkshire pudding",
        "bao bun",
        "ezekiel bread",
        "arabic bread",
        "zwieback",
        "coconut wraps",
        "oven chips",
        "taco kit",
        "breading mix",
        "gluten free pita",
        "ready-made arepas",
        "ready-made pancake",
        "japanese peanuts",
        "potato waffle",
        "tartlet shells",
        "cauliflower wraps",
        "injera",
        "melinjo crackers"
    ],
    "Oils & Fats": [
        "olive oil",
        "vegetable oil",
        "extra virgin olive oil",
        "canola oil",
        "coconut oil",
        "cooking spray",
        "sesame oil",
        "frying oil",
        "sunflower oil",
        "avocado oil",
        "toasted sesame oil",
        "peanut oil",
        "grapeseed oil",
        "lard",
        "corn oil",
        "virgin coconut oil",
        "mustard oil",
        "chili oil",
        "walnut oil",
        "truffle oil",
        "bacon grease",
        "safflower oil",
        "cacao butter",
        "salad oil",
        "garlic oil",
        "duck fat",
        "rice bran oil",
        "soybean oil",
        "white truffle oil",
        "flaxseed oil",
        "butter-flavored cooking spray",
        "medium-chain triglyceride",
        "pumpkin seed oil",
        "hazelnut oil",
        "coconut oil spray",
        "almond oil",
        "lemon oil",
        "macadamia oil",
        "goose fat",
        "basil oil",
        "pork fat",
        "palm oil",
        "beef dripping",
        "schmaltz",
        "tallow",
        "sushi vinegar",
        "pistachio oil",
        "argan oil",
        "beef fat",
        "pecan oil",
        "herb-infused olive oil",
        "crisco oil",
        "red palm oil",
        "lamb fat",
        "shea butter",
        "shallot oil",
        "castor oil",
        "chicken drippings",
        "achiote oil",
        "ginger oil",
        "jojoba oil",
        "oregano oil",
        "hemp seed oil",
        "wheat germ oil",
        "cottonseed oil",
        "pork dripping",
        "rosehip seed oil",
        "camelina oil",
        "marula oil",
        "moringa seed oil",
        "white cacao butter",
        "black seed oil"
    ],
    "Dressings & Vinegars": [
        "mayonnaise",
        "apple cider vinegar",
        "balsamic vinegar",
        "vinegar",
        "red wine vinegar",
        "rice wine vinegar",
        "white wine vinegar",
        "ranch dressing",
        "italian dressing",
        "sherry vinegar",
        "sweet chilli sauce",
        "white balsamic vinegar",
        "champagne vinegar",
        "vinaigrette dressing",
        "balsamic vinaigrette",
        "blue cheese dressing",
        "thousand island",
        "malt vinegar",
        "caesar dressing",
        "black vinegar",
        "canola mayonnaise",
        "raspberry vinegar",
        "japanese mayonnaise",
        "tarragon vinegar",
        "greek vinaigrette",
        "sesame dressing",
        "honey mustard dressing",
        "aioli sauce",
        "french dressing",
        "spicy mayo",
        "poppyseed dressing",
        "catalina dressing",
        "verjuice",
        "raspberry vinaigrette",
        "cane vinegar",
        "red wine vinaigrette",
        "russian dressing",
        "avocado oil mayonnaise",
        "champagne vinaigrette",
        "garlic mayonnaise",
        "brown rice vinegar",
        "sun-dried tomato vinaigrette",
        "ume plum vinegar",
        "coconut vinegar",
        "buttermilk ranch dressing",
        "cilantro dressing",
        "fig balsamic",
        "creamy dressing",
        "miso dressing",
        "onion salad dressing",
        "white balsamic vinaigrette",
        "chardonnay vinegar",
        "green goddess dressing",
        "prepared coleslaw dressing",
        "honey vinegar",
        "tandoori mayonnaise",
        "vinegar powder",
        "chili vinegar",
        "moscatel vinegar",
        "caramelised onion dressing",
        "chili-lime dressing",
        "sugarcane vinegar",
        "spicy vinegar",
        "pineapple vinegar"
    ],
    "Condiments": [
        "soy sauce",
        "dijon mustard",
        "worcestershire",
        "hot sauce",
        "ketchup",
        "mustard",
        "fish sauce",
        "bbq sauce",
        "sriracha",
        "applesauce",
        "wholegrain mustard",
        "tamari",
        "oyster sauce",
        "ginger-garlic paste",
        "chili sauce",
        "brown mustard",
        "teriyaki sauce",
        "prepared horseradish",
        "ginger paste",
        "buffalo sauce",
        "dark soy sauce",
        "chili paste",
        "coconut aminos",
        "harissa",
        "cranberry sauce",
        "tamarind paste",
        "chili-garlic sauce",
        "pomegranate molasses",
        "gochujang",
        "wasabi",
        "honey mustard",
        "mango chutney",
        "english mustard",
        "preserved lemon",
        "sambal oelek",
        "kecap manis",
        "chutney",
        "shrimp paste",
        "picante sauce",
        "thai sweet chili sauce",
        "sweet and sour sauce",
        "liquid aminos",
        "tartar sauce",
        "chili-garlic paste",
        "green chutney",
        "bonito flakes",
        "ponzu",
        "mexican hot sauce",
        "green chilli sauce",
        "sambal",
        "crispy onions",
        "red pepper jelly",
        "green chilli paste",
        "peri peri",
        "mint jelly",
        "jalapeno jelly",
        "thai chili paste",
        "mustard paste",
        "horseradish mustard",
        "aji amarillo",
        "pepper paste",
        "yuzu juice",
        "hot pepper jelly",
        "chili jam",
        "tamarind chutney",
        "tonkatsu sauce",
        "chermoula",
        "onion marmalade",
        "hp sauce",
        "duck sauce",
        "ginger chili paste",
        "giardiniera",
        "doubanjiang",
        "korean bbq sauce",
        "lime pickle",
        "black soy sauce",
        "maggi sauce",
        "bacon jam",
        "chinese mustard",
        "chamoy",
        "doenjang",
        "karashi",
        "chili crisp",
        "mushroom soy sauce",
        "yuzu kosho",
        "german mustard",
        "taucheo",
        "hot bean paste",
        "remoulade",
        "white bbq sauce",
        "eel sauce",
        "pickapeppa sauce",
        "salsa lizano",
        "patis",
        "shrimp sauce",
        "sweet soybean paste",
        "grape must",
        "banana ketchup",
        "shrimp powder",
        "green harissa"
    ],
    "Canned Food": [
        "canned tomato",
        "capers",
        "green olives",
        "canned chickpea",
        "black olives",
        "canned black beans",
        "canned pumpkin",
        "kalamata olives",
        "canned tuna",
        "pickle",
        "canned pineapple",
        "canned anchovy",
        "chipotle in adobo",
        "canned artichoke",
        "canned corn",
        "canned kidney beans",
        "canned cannellini beans",
        "refried beans",
        "canned whole tomato",
        "sweet pickle relish",
        "sauerkraut",
        "creamed corn",
        "corned beef",
        "canned beans",
        "pickled jalapenos",
        "diced green chiles",
        "sun-dried tomatoes in oil",
        "kimchi",
        "chili beans",
        "bamboo shoot",
        "baked beans",
        "canned mushroom",
        "canned salmon",
        "canned peaches",
        "pickling juice",
        "dill pickle relish",
        "canned black-eyed peas",
        "pickled ginger",
        "canned green beans",
        "spam",
        "canned clam",
        "chili with beans",
        "pickled onions",
        "canned lentils",
        "fruit cocktail",
        "canned peas",
        "pimiento-stuffed green olives",
        "canned cherry tomato",
        "pickled red onion",
        "canned pork",
        "pickled beets",
        "jarred roasted red bell pepper",
        "bread &amp; butter pickles",
        "canned pear",
        "peppadew pepper",
        "onion paste",
        "pickled vegetables",
        "canned baby corn",
        "mexican-style corn",
        "chili without beans",
        "ranch-style beans",
        "pork and beans",
        "canned chicken breast",
        "canned lychee",
        "banana pepper rings",
        "canned sardines",
        "pickled pepper",
        "tomato relish",
        "canned jackfruit",
        "taggiasca olives",
        "canned sweet potato",
        "canned carrot",
        "red pepper relish",
        "fire-roasted green chiles",
        "corn relish",
        "pickled hot pepper",
        "pickled cherry peppers",
        "canned mackerel",
        "candied jalapenos",
        "canned pimento",
        "okra pickles",
        "umeboshi",
        "canned potato",
        "tomato confit",
        "canned four-bean mix",
        "piccalilli",
        "pickled green beans",
        "half-sour pickle",
        "pickled radish",
        "myoga",
        "sardines in tomato sauce",
        "pickled sport peppers",
        "fermented pickle",
        "mango pickles",
        "yellow pickled radish",
        "mustard pickles",
        "tuna spread",
        "zha cai",
        "pickled garlic",
        "szechuan preserved vegetable"
    ],
    "Sauces, Spreads & Dips": [
        "peanut butter",
        "tomato paste",
        "tomato sauce",
        "salsa",
        "tahini",
        "pesto",
        "marinara sauce",
        "pasta sauce",
        "hoisin sauce",
        "tomatoes with green chiles",
        "pico de gallo",
        "stewed tomatoes",
        "hummus",
        "guacamole",
        "enchilada sauce",
        "fire-roasted tomato",
        "salsa verde",
        "alfredo sauce",
        "balsamic glaze",
        "anchovy paste",
        "red enchilada sauce",
        "steak sauce",
        "chunky peanut butter",
        "tzatziki",
        "beef gravy",
        "taco sauce",
        "sun-dried tomato pesto",
        "b\u00e9chamel sauce",
        "horseradish sauce",
        "plum sauce",
        "garlic butter",
        "hollandaise sauce",
        "cocktail sauce",
        "black bean sauce",
        "cheese dip",
        "tapenade",
        "turkey gravy",
        "stir-fry sauce",
        "thai peanut sauce",
        "chicken gravy",
        "sloppy joe sauce",
        "mustard sauce",
        "pimento cheese spread",
        "sofrito",
        "sun-dried tomato paste",
        "demi-glace",
        "queso dip",
        "chimichurri sauce",
        "french onion dip",
        "bolognese sauce",
        "curry sauce",
        "liver spread",
        "schezwan sauce",
        "mushroom gravy",
        "browning sauce",
        "pork gravy",
        "orange sauce",
        "country gravy",
        "pineapple salsa",
        "artichoke dip",
        "olive paste",
        "black truffle butter",
        "mango salsa",
        "japanese curry",
        "spinach dip",
        "tikka masala sauce",
        "vodka sauce",
        "sesame sauce",
        "kung pao sauce",
        "mole paste",
        "onion gravy",
        "sausage gravy",
        "whipped cream cheese spread",
        "cheese spread",
        "deviled ham spread",
        "garlic spread",
        "pad thai sauce",
        "green olive tapenade",
        "butter chicken sauce",
        "black pepper sauce",
        "char siu sauce",
        "garlic pasta sauce",
        "schezwan chutney",
        "mentsuyu",
        "black bean and corn salsa",
        "tarama",
        "ssamjang",
        "thai red curry sauce",
        "white pizza sauce",
        "tomato tapenade",
        "yum yum sauce",
        "honey garlic sauce",
        "mole sauce",
        "nuoc cham",
        "white clam sauce",
        "bean dip",
        "eggplant dip",
        "salsa macha",
        "b\u00e9arnaise sauce",
        "duck liver p\u00e2t\u00e9"
    ],
    "Soups, Stews & Stocks": [
        "chicken broth",
        "vegetable broth",
        "chicken stock",
        "beef broth",
        "beef stock",
        "cream of mushroom",
        "cream of chicken",
        "bouillon cube",
        "onion soup mix",
        "tomato soup",
        "fish stock",
        "cream of celery",
        "better than bouillon",
        "clam juice",
        "cheese soup",
        "bone broth",
        "dashi",
        "onion soup",
        "chicken soup",
        "veal stock",
        "chicken bone broth",
        "turkey stock",
        "lamb stock",
        "turkey broth",
        "beef consomm\u00e9",
        "stock paste",
        "cream of potato",
        "golden mushroom soup",
        "seafood stock",
        "mushroom broth",
        "vegetable soup",
        "vegetable soup mix",
        "chicken noodle soup",
        "chicken consomm\u00e9",
        "shrimp stock",
        "nacho cheese soup",
        "ramen noodle soup",
        "pork stock",
        "cream of broccoli",
        "lobster stock",
        "chicken rice soup",
        "beefy onion soup mix",
        "butternut squash soup",
        "chicken stock paste",
        "miso soup",
        "clam broth",
        "broccoli-cheese soup",
        "clam chowder",
        "duck stock",
        "cream of asparagus",
        "vegan chicken broth",
        "ham stock",
        "beefy mushroom soup",
        "pork broth",
        "bean soup mix",
        "cream of shrimp soup",
        "lentil soup",
        "veal broth",
        "vegetable beef soup",
        "cream of bacon",
        "lobster bisque",
        "bean with bacon soup",
        "condensed chicken gumbo soup",
        "turkey bone broth",
        "minestrone",
        "bovril",
        "lamb broth",
        "thai chicken broth",
        "tomato bisque",
        "venison stock",
        "beef stock paste",
        "pork &amp; beans",
        "sun-dried tomato bisque mix",
        "callaloo",
        "ham-flavored concentrate",
        "oxtail soup",
        "potato soup mix",
        "pho broth",
        "split pea soup",
        "tortilla soup base",
        "chicken and mushroom soup",
        "chili beef soup",
        "cream of cauliflower",
        "dashida",
        "green pea soup"
    ],
    "Desserts & Sweet Snacks": [
        "cocoa",
        "dark chocolate",
        "chocolate",
        "graham cracker",
        "baking chocolate",
        "marshmallow",
        "white chocolate",
        "oreo",
        "chocolate hazelnut spread",
        "dutch-process cocoa",
        "instant pudding",
        "chocolate candy",
        "cacao",
        "raspberry jam",
        "apricot jam",
        "caramel sauce",
        "strawberry jam",
        "candy coating",
        "biscuits",
        "marshmallow creme",
        "candy",
        "jam",
        "orange marmalade",
        "wafer",
        "cookies",
        "chocolate pudding",
        "peanut butter cups",
        "candy cane",
        "dark cocoa",
        "cacao nibs",
        "ginger snaps",
        "lady fingers",
        "chocolate chip cookies",
        "digestive biscuits",
        "fudge sauce",
        "chocolate cookies",
        "apple butter",
        "peppermint candy",
        "dark chocolate cocoa powder",
        "cinnamon roll",
        "butter cookies",
        "candied cherry",
        "vanilla pudding",
        "caramel candies",
        "currant jelly",
        "candied ginger",
        "angel food cake",
        "peach preserves",
        "candied peel",
        "chocolate wafer",
        "cherry jam",
        "dark couverture chocolate",
        "couverture chocolate",
        "grape jelly",
        "waffles",
        "instant lemon pudding",
        "butterscotch",
        "fig jam",
        "blueberry jam",
        "cookie butter",
        "candied fruit",
        "almond cookies",
        "blackberry preserves",
        "apple jelly",
        "gummies",
        "candy corn",
        "sugar cookies",
        "ice-cream cone",
        "marmalade",
        "strawberry puree",
        "chocolate powder",
        "sponge cake",
        "chocolate-covered espresso bean",
        "pineapple jam",
        "licorice",
        "egg candies",
        "plum jam",
        "mexican chocolate",
        "sorbet",
        "white couverture",
        "banana pudding",
        "chocolate peanut butter",
        "guava paste",
        "cinnamon candy",
        "pumpkin butter",
        "fudge",
        "strawberry sauce",
        "chocolate spread",
        "doughnut",
        "butterscotch pudding mix",
        "biscotti",
        "peppermint patties",
        "raspberry sorbet",
        "cheesecake instant pudding",
        "pistachio pudding",
        "raspberry sauce",
        "chocolate fudge",
        "hershey kisses",
        "pistachio instant pudding",
        "praline"
    ],
    "Wine, Beer & Spirits": [
        "white wine",
        "red wine",
        "whisky",
        "rum",
        "vodka",
        "beer",
        "orange liqueur",
        "cider",
        "tequila",
        "sherry",
        "gin",
        "brandy",
        "bitters",
        "mirin",
        "white rum",
        "coffee liqueur",
        "champagne",
        "irish cream",
        "vermouth",
        "amaretto",
        "marsala wine",
        "cognac",
        "sparkling wine",
        "sake",
        "rice wine",
        "shaoxing wine",
        "dry vermouth",
        "liqueur",
        "coconut rum",
        "dessert wine",
        "curacao",
        "port wine",
        "kirsch",
        "peach schnapps",
        "apple brandy",
        "ros\u00e9 wine",
        "anise liqueur",
        "herbal liqueur",
        "cooking wine",
        "limoncello",
        "elderflower liqueur",
        "hazelnut liqueur",
        "peach liqueur",
        "melon liqueur",
        "raspberry liqueur",
        "madeira wine",
        "schnapps",
        "banana liqueur",
        "creme de cacao",
        "absinthe",
        "aperol",
        "white cooking wine",
        "vanilla vodka",
        "cinnamon alcohol",
        "creme de menthe",
        "apricot brandy",
        "cacha\u00e7a",
        "elderflower cordial",
        "chocolate liqueur",
        "ginger liqueur",
        "sloe gin",
        "maraschino",
        "creme de cassis",
        "cream sherry",
        "bloody mary mix",
        "gold rum",
        "sparkling ros\u00e9",
        "red cooking wine",
        "grappa",
        "lime cordial",
        "mezcal",
        "strawberry liqueur",
        "drambuie",
        "ginger wine",
        "white port",
        "pumpkin ale",
        "peppermint liqueur",
        "advocaat",
        "pi\u00f1a colada mix",
        "b\u00e9n\u00e9dictine",
        "daiquiri mix",
        "coconut liqueur",
        "galliano",
        "plum wine",
        "pisco",
        "chocolate bitters",
        "vanilla liqueur",
        "rumchata liqueur",
        "sangria",
        "grapefruit bitters",
        "peach brandy",
        "white chocolate liqueur",
        "rhum agricole",
        "apple liqueur",
        "moonshine",
        "bergamot liqueur",
        "cherry vodka",
        "violette liqueur",
        "armagnac",
        "soju"
    ],
    "Beverages": [
        "orange juice",
        "coffee",
        "club soda",
        "espresso",
        "pineapple juice",
        "apple juice",
        "tea",
        "cranberry juice",
        "tomato juice",
        "coconut water",
        "pomegranate juice",
        "grapefruit juice",
        "lemonade",
        "coke",
        "eggnog",
        "ginger ale",
        "ginger beer",
        "orange juice concentrate",
        "lemon lime soda",
        "cream of coconut",
        "sprite",
        "green tea",
        "lemonade concentrate",
        "chai tea",
        "root beer",
        "drinking chocolate",
        "tonic water",
        "malted milk powder",
        "mango juice",
        "sour mix",
        "hibiscus tea",
        "tea leaves",
        "grape juice",
        "carrot juice",
        "cherry juice",
        "limeade concentrate",
        "dr pepper",
        "white grape juice",
        "tangerine juice",
        "fruit juice",
        "watermelon juice",
        "apricot juice",
        "passion-fruit juice",
        "iced tea",
        "kombucha",
        "beet juice",
        "peach juice",
        "orange soda",
        "margarita mix",
        "kool aid",
        "energy drink",
        "pear juice",
        "chamomile tea",
        "tamarind juice",
        "tamarind water",
        "cream soda",
        "mountain dew",
        "rooibos tea",
        "grapefruit soda",
        "jasmine tea",
        "raspberry juice",
        "guava juice",
        "clamato",
        "iced coffee concentrate",
        "green tea leaves",
        "rose syrup",
        "strawberry juice",
        "blueberry juice",
        "lemonade mix",
        "v8 juice",
        "thai tea",
        "aloe vera juice",
        "white tea",
        "juice blend",
        "prune juice",
        "sparkling cider",
        "lapsang souchong",
        "passion tea",
        "berry juice",
        "butterfly pea flower",
        "strawberry soda",
        "blackcurrant juice",
        "herbal tea",
        "lychee juice",
        "sugar cane juice",
        "banana juice",
        "cranberry-raspberry juice",
        "decaf coffee",
        "pumpkin spice coffee",
        "lime soda",
        "pepsi",
        "peppermint tea",
        "sports drink",
        "lemon crystals",
        "acai berry juice",
        "chicory coffee",
        "kiwi juice",
        "apple tea",
        "golden milk powder",
        "pineapple soda"
    ],
    "Supplements & Extracts": [
        "almond extract",
        "food coloring",
        "nutritional yeast",
        "peppermint extract",
        "protein powder",
        "lemon extract",
        "coconut extract",
        "rose water",
        "orange extract",
        "rum extract",
        "maple extract",
        "collagen",
        "chocolate protein powder",
        "orange blossom water",
        "liquid egg white",
        "peanut butter powder",
        "essence",
        "vegan protein powder",
        "maca powder",
        "spirulina",
        "coffee extract",
        "strawberry extract",
        "brewer's yeast",
        "butter extract",
        "chocolate extract",
        "bee pollen",
        "raspberry extract",
        "anise extract",
        "banana extract",
        "lavender oil",
        "cannabis",
        "essential oil",
        "chicken essence",
        "vitamin c",
        "egg white powder",
        "caramel extract",
        "cannabutter",
        "root beer extract",
        "acai powder",
        "ube flavoring",
        "glucomannan",
        "hazelnut extract",
        "tamarind extract",
        "freeze-dried strawberry powder",
        "cherry extract",
        "butterscotch flavor",
        "lemon juice concentrate",
        "pineapple extract",
        "kewra water",
        "chocolate collagen",
        "raspberry powder",
        "cannabis milk",
        "cinnamon extract",
        "malt extract",
        "kombucha starter",
        "soy lecithin",
        "camu powder",
        "pandan extract",
        "wheatgrass powder",
        "ashwagandha",
        "casein",
        "chlorella",
        "fish oil",
        "probiotics",
        "cbd",
        "lime essential oil",
        "activated charcoal",
        "egg powder",
        "wine yeast",
        "barley grass",
        "greens powder",
        "reishi mushroom",
        "rice protein powder",
        "tea-tree oil",
        "vitamin d",
        "calcium lactate",
        "magnesium",
        "mango extract",
        "berry powder",
        "blueberry extract",
        "corn extract",
        "vitamin e",
        "creatine",
        "daily vitamins",
        "moringa powder",
        "pure lime extract",
        "sodium alginate",
        "sunflower lecithin",
        "thc",
        "champagne yeast",
        "rose oil",
        "banana powder",
        "chaga mushroom powder",
        "cranberry powder",
        "eucalyptus oil",
        "goji berry powder",
        "maltodextrin",
        "bubblegum essence",
        "butterfly pea powder",
        "cake batter extract"
    ]
};